Repository redacademy/voicestory-winter-2020, pull requests merged in 2020-04, with the labels that each got.

#100 Kd feature proptypes
  client/js/components/Button/Button.js
  client/js/components/Collapsible/Collapsible.js
  client/js/components/CustomText/CustomText.js
  client/js/components/Error/Error.js
  client/js/components/EventCard/EventCard.js
  client/js/components/LoginForm/LoginForm.js
  client/js/components/LoginForm/LoginFormMutation.js
  client/js/components/NotificationBanner/NotificationBanner.js
  client/js/components/NotificationsList/NotificationsList.js
  client/js/components/SignUpForm/SignUpForm.js
  client/js/components/SignUpForm/SignUpFormMutation.js
  client/js/components/SpeakerCard/SpeakerCard.js
  client/js/components/ThemesButton/ThemesButton.js
  client/js/components/VideoCard/VideoCard.js
  client/js/components/VideoList/VideoList.js
  client/js/context/FavesContext/FavesContext.js
  client/js/context/UserContext/UserContext.js
  client/js/context/YoutubeData/YoutubeDataContext.js
  client/js/screens/AboutUs/AboutUs.js
  client/js/screens/AboutUs/AboutUsContainer.js
  client/js/screens/Application/Application.js
  client/js/screens/Application/ApplicationContainer.js
  client/js/screens/Checkout/Checkout.js
  client/js/screens/Checkout/CheckoutContainer.js
  client/js/screens/CheckoutConfirmation/CheckoutConfirmation.js
  client/js/screens/CheckoutConfirmation/CheckoutConfirmationContainer.js
  client/js/screens/ContactUs/ContactUs.js
  client/js/screens/ContactUs/ContactUsContainer.js
  client/js/screens/EventInfo/EventInfo.js
  client/js/screens/EventInfo/EventInfoContainer.js
  client/js/screens/Events/Events.js
  client/js/screens/Events/EventsContainer.js
  client/js/screens/Explore/Explore.js
  client/js/screens/Explore/ExploreContainer.js
  client/js/screens/FAQ/FAQ.js
  client/js/screens/FAQ/FAQContainer.js
  client/js/screens/Faves/Faves.js
  client/js/screens/Faves/FavesContainer.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
Labels: documentation, enhancement

#101 Kd bug fixes
  README.md
  client/js/components/VideoList/VideoList.js
  client/js/components/VideoList/styles.js
  client/js/screens/Video/styles.js
Labels: bug

#102 Ivan proptypes
  client/js/screens/Theme/Theme.js
  client/js/screens/Theme/ThemeContainer.js
  client/js/screens/Themes/ThemesContainer.js
  client/js/screens/Ticket/Ticket.js
  client/js/screens/Ticket/TicketContainer.js
  client/js/screens/TicketInfo/TicketInfo.js
  client/js/screens/TicketInfo/TicketInfoContainer.js
  client/js/screens/Tickets/Tickets.js
  client/js/screens/Tickets/TicketsContainer.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/Video/Video.js
  client/js/screens/Video/VideoContainer.js
Labels: bug

#103 Ivan signup error
  client/js/components/SignUpForm/SignUpForm.js
  client/js/screens/UserProfile/UserProfile.js
Labels: bug

#105 Id feature eventcard
  client/js/components/EventCard/EventCard.js
  client/js/components/EventCard/styles.js
  client/js/navigation/Navigation.js
  client/js/screens/Events/Events.js
  client/js/screens/Events/EventsContainer.js
  client/js/screens/Tickets/Tickets.js
  client/js/screens/Tickets/TicketsContainer.js
Labels: enhancement

#107 Kd bug fixes
  client/js/components/EventCard/EventCard.js
  client/js/components/VideoList/VideoList.js
  client/js/screens/CheckoutConfirmation/CheckoutConfirmationContainer.js
Labels: bug

#108 Ivan signup error
  client/js/screens/CheckoutConfirmation/CheckoutConfirmationContainer.js
  client/js/screens/Tickets/TicketsContainer.js
Labels: bug

#109 Kd bug fixes
  client/js/navigation/Navigation.js
  client/js/screens/TicketInfo/TicketInfo.js
Labels: bug
