Repository redacademy/voicestory-winter-2020, pull requests merged in 2020-03, with the labels that each got.

#6 Kh navigation
  client/App.js
  client/ios/Podfile.lock
  client/ios/voicestoryWinter2020.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client/ios/voicestoryWinter2020.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  client/js/navigation/Navigation.js
  client/js/navigation/config.js
  client/js/navigation/index.js
  client/js/screens/Events/Events.js
  client/js/screens/Events/EventsContainer.js
  client/js/screens/Events/index.js
  client/js/screens/Events/styles.js
  client/js/screens/Explore/Explore.js
  client/js/screens/Explore/ExploreContainer.js
  client/js/screens/Explore/index.js
  client/js/screens/Explore/styles.js
  client/js/screens/Tickets/Tickets.js
  client/js/screens/Tickets/TicketsContainer.js
  client/js/screens/Tickets/index.js
  client/js/screens/Tickets/styles.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/UserProfile/index.js
  client/js/screens/UserProfile/styles.js
  node_modules/.yarn-integrity
  yarn.lock
Labels: enhancement

#25 Ivan prisma schema
  server/datamodel.prisma
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/index.js
  server/generated/prisma-client/prisma-schema.js
  server/prisma.yml
Labels: good first issue

#30 Modifies the existing schema for Location and Speaker
  server/datamodel.prisma
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/index.js
  server/generated/prisma-client/prisma-schema.js
Labels: enhancement

#35 Id feature eventcard
  .gitignore
  client/js/components/EventCard/EventCard.js
  client/js/components/EventCard/index.js
  client/js/components/EventCard/styles.js
  client/js/components/Loader/Loader.js
  client/js/components/Loader/index.js
  client/js/components/Loader/styles.js
  client/js/components/LoginForm/LoginForm.js
  client/js/components/LoginForm/index.js
  client/js/components/LoginForm/styles.js
  client/js/components/SignUpForm/SignUp.js
  client/js/components/SignUpForm/index.js
  client/js/components/SignUpForm/styles.js
  client/js/screens/Events/Events.js
  client/js/screens/Events/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Home/index.js
  client/js/screens/Home/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#36 Ivan profile
  client/config/api.js
  client/js/App.js
  client/js/screens/UserProfile/UserProfile.js
  client/js/screens/UserProfile/UserProfileContainer.js
  client/js/screens/UserProfile/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#39 Kd feature videos
  client/ios/Podfile.lock
  client/js/components/VideoCard/VideoCard.js
  client/js/components/VideoCard/styles.js
  client/js/components/VideoList/VideoList.js
  client/js/components/VideoList/styles.js
  client/js/screens/Explore/Explore.js
  client/js/screens/Explore/ExploreContainer.js
  client/js/screens/Video/VideoContainer.js
  client/js/screens/Videos/Videos.js
  client/js/screens/Videos/VideosContainer.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#41 Added linkage to event info page
  client/js/components/EventCard/EventCard.js
  client/js/screens/Events/Events.js
  client/js/screens/Events/EventsContainer.js
Labels: enhancement

#46 Pulling image from database
  .gitignore
  client/js/components/EventCard/EventCard.js
Labels: enhancement

#48 Change refactor to speaker card to handle logic to populate card
  client/js/components/SpeakerCard/SpeakerCard.js
Labels: enhancement

#47 Id feature eventpage
  .DS_Store
  client/js/screens/EventInfo/EventInfo.js
  client/js/screens/EventInfo/EventInfoContainer.js
  client/js/screens/EventInfo/styles.js
  client/js/screens/Events/EventsContainer.js
Labels: enhancement

#50 Id feature speakercard
  client/js/components/SpeakerCard/SpeakerCard.js
Labels: bug

#51 id-feature-speakerprofile
  client/js/screens/Events/EventsContainer.js
  client/js/screens/SpeakerProfile/SpeakerProfile.js
  client/js/screens/SpeakerProfile/SpeakerProfileContainer.js
  client/js/screens/SpeakerProfile/styles.js
Labels: enhancement

#52 Add open maps feature using google geocoder api
  client/config/models.js
  client/js/screens/EventInfo/EventInfo.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#54 Ivan server auth
  client/package.json
  client/yarn.lock
  server/datamodel.prisma
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/prisma-schema.js
  server/index.js
  server/package.json
  server/resolvers.js
  server/typeDefs.js
  server/yarn.lock
Labels: enhancement

#59 Ivan client auth
  client/js/App.js
  client/js/components/LoginForm/LoginForm.js
  client/js/components/LoginForm/LoginFormMutation.js
  client/js/components/LoginForm/index.js
  client/js/components/SignUpForm/SignUpForm.js
  client/js/context/UserContext/UserContext.js
  client/js/context/UserContext/index.js
  client/js/navigation/index.js
  client/yarn.lock
  server/datamodel.prisma
  server/resolvers.js
  server/typeDefs.js
Labels: documentation

#61 id-feature-speakerprofile
  client/js/navigation/Navigation.js
  client/js/screens/SpeakerProfile/SpeakerProfile.js
  client/js/screens/SpeakerProfile/styles.js
Labels: enhancement

#63 Id feature eventpage
  client/js/screens/EventInfo/styles.js
  client/js/screens/Events/EventsContainer.js
Labels: bug

#64 Ivan client auth
  client/js/components/SignUpForm/SignUpFormMutation.js
  client/js/components/SignUpForm/index.js
  server/datamodel.prisma
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/index.js
  server/generated/prisma-client/prisma-schema.js
  server/resolvers.js
Labels: enhancement

#69 Ivan client auth
  client/js/components/LoginForm/LoginFormMutation.js
  client/js/components/SignUpForm/SignUpForm.js
  client/js/components/SignUpForm/SignUpFormMutation.js
  client/js/screens/Login/Login.js
  server/resolvers.js
  server/typeDefs.js
Labels: enhancement

#72 Ivan all speakers
  client/js/components/Loader/styles.js
  client/js/screens/Speakers/Speakers.js
  client/js/screens/Speakers/SpeakersContainer.js
  client/js/screens/Speakers/styles.js
Labels: enhancement

#65 Kd feature videos
  client/js/App.js
  client/js/assets/icons/whiteHeart-x1.png
  client/js/assets/icons/whiteHeart-x2.png
  client/js/components/ThemesButton/ThemesButton.js
  client/js/components/VideoCard/VideoCard.js
  client/js/components/VideoList/VideoList.js
  client/js/context/YoutubeData/YoutubeDataContext.js
  client/js/context/YoutubeData/index.js
  client/js/navigation/Navigation.js
  client/js/screens/Explore/Explore.js
  client/js/screens/Faves/Faves.js
  client/js/screens/MostViewed/MostViewed.js
  client/js/screens/MostViewed/MostViewedContainer.js
  client/js/screens/Newest/Newest.js
  client/js/screens/Newest/NewestContainer.js
  client/js/screens/Speakers/SpeakersContainer.js
  client/js/screens/Theme/Theme.js
  client/js/screens/Theme/ThemeContainer.js
  client/js/screens/Theme/index.js
  client/js/screens/Theme/styles.js
  client/js/screens/Themes/Themes.js
  client/js/screens/Themes/ThemesContainer.js
  client/js/screens/Video/Video.js
  client/js/screens/Video/VideoContainer.js
  client/js/screens/Video/styles.js
  client/js/screens/VideoPlayer/VideoPlayer.js
  client/js/screens/VideoPlayer/styles.js
  client/js/screens/Videos/Videos.js
  client/package.json
  client/yarn.lock
Labels: bug, enhancement

#75 Kd feature videos
  client/js/screens/Video/Video.js
Labels: bug

#76 Removes location from existing queries
  client/js/screens/Events/EventsContainer.js
  client/js/screens/Tickets/TicketsContainer.js
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/prisma-schema.js
Labels: enhancement

#77 Kd feature maps
  client/js/screens/EventInfo/EventInfo.js
  client/js/screens/TicketInfo/TicketInfo.js
Labels: bug, enhancement

#81 Kd feature videos
  client/js/components/Error/Error.js
  client/js/components/Error/index.js
  client/js/components/Error/styles.js
  client/js/screens/Explore/Explore.js
  client/js/screens/MostViewed/MostViewed.js
  client/js/screens/Newest/Newest.js
  client/js/screens/Theme/Theme.js
  client/js/screens/Video/VideoContainer.js
Labels: bug

#82 Kd bug fixes
  client/js/components/Error/styles.js
  client/js/context/YoutubeData/YoutubeDataContext.js
  client/js/screens/Explore/Explore.js
Labels: bug

#83 Id feature eventpage
  client/js/components/EventCard/EventCard.js
  client/js/navigation/Navigation.js
  client/js/screens/EventInfo/EventInfo.js
  client/js/screens/EventInfo/styles.js
Labels: bug

#86 Kd bug fixes
  client/js/context/YoutubeData/YoutubeDataContext.js
Labels: bug

#87 Kd bug fixes
  client/js/screens/Explore/Explore.js
  client/js/screens/Explore/ExploreContainer.js
Labels: bug, enhancement

#88 Kd bug fixes
  client/js/components/NotificationBanner/NotificationBanner.js
  client/js/components/NotificationBanner/styles.js
  client/js/components/NotificationsList/NotificationsList.js
  client/js/screens/Notification/Notification.js
  client/js/screens/Notification/NotificationContainer.js
  client/js/screens/Notification/index.js
Labels: bug, enhancement

#89 Kd feature videos
  client/js/screens/Theme/Theme.js
Labels: bug

#90 Kd bug fixes
  client/js/screens/UserProfile/UserProfileContainer.js
Labels: bug

#93 Update readme
  README.md
Labels: documentation

#95 Kd bug fixes
  client/js/components/Error/styles.js
  client/js/components/VideoList/styles.js
  client/js/navigation/Navigation.js
  client/js/screens/Checkout/CheckoutContainer.js
  client/js/screens/EventInfo/EventInfoContainer.js
  client/js/screens/Faves/Faves.js
  client/js/screens/Faves/styles.js
  client/js/screens/Search/Search.js
  client/js/screens/Search/SearchContainer.js
  client/js/screens/Ticket/Ticket.js
  client/js/screens/Ticket/TicketContainer.js
  client/js/screens/TicketInfo/TicketInfoContainer.js
  client/js/screens/Video/Video.js
  client/js/screens/Video/VideoContainer.js
  client/js/screens/Videos/Videos.js
  client/js/screens/Videos/VideosContainer.js
  client/js/screens/Videos/styles.js
Labels: bug

#96 Ivan login error
  client/js/components/SignUpForm/SignUpForm.js
  client/js/components/SignUpForm/SignUpFormMutation.js
Labels: bug

#97 Kd bug fixes
  client/js/screens/Video/Video.js
Labels: bug

#99 Adds deleting previous user data at sign out
  client/js/navigation/TopDrawer.js
  client/js/navigation/config.js
Labels: bug
